name: auto-add-label

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  sync:
    name: auto add label
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.GITHUB_TOKEN }}
      ISSUE_LABEL: "type;priority"
      PR_LABEL: "type;priority;day"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: qianbd/auto_label@feat-add-code
